### PR TITLE
Add retry to all Kafka producers

### PR DESCRIPTION
**Pull request by cb372**
Try 5 times with 1 second pause in between.

TODO: all the config-loading code in the Main class is getting pretty horrendous. We should use [pureconfig](https://github.com/melrief/pureconfig).

### CODE REVIEW

**Comment by cb372** [comment]
On second thought, maybe an exponential backoff is more appropriate here?

**Comment by fleetwoods** [comment]
Yeah, like what Mailgun do, I like it

**Comment by fleetwoods** [comment]
Code that is there now is 👍

**Comment by ovo-comms-circleci** [comment]
This PR was successfully deployed to production by [CircleCI build 160](https://circleci.com/gh/ovotech/comms-orchestration/160) at 2017-03-16 11:00 GMT.

**Pull request merged**
